### PR TITLE
Figs

### PR DESCRIPTION
**Pull request by jaybee84**
Adding Fig2 and updated Fig3

### CODE REVIEW

**Comment by allaway** [comment]
> Fig2B : can you change the colors to match the tumor type color scheme?
> Also, can you remove the `` ` `` from the LVs in the ridgeplots? here's a snippet to do that: `` mutate(lv_fix = stringr::str_replace_all(LV_Full,"`` `` ``",""))` (I just had this handy from doing the same this morning :) )
> 
> Figure 2: Looks good, can you make the abstract section a bit denser? Can you add something to clarify that you are testing on an independent set that was not used for feature selection in (iv/v)?
> 
> Figure 3: same comments as 2B.

This is a really hard comment to format with all the backticks but hopefully it's easy enough to copy and paste...haha

**Comment by sgosline** [comment]
I agree with Robert's suggestions.

**Comment by jaybee84** [comment]
merging this closes #63

**Comment by jaybee84** [comment]
> > Fig2B : can you change the colors to match the tumor type color scheme?
> > Also, can you remove the `` ` `` from the LVs in the ridgeplots? here's a snippet to do that: ` mutate(lv_fix = stringr::str_replace_all(LV_Full,"` ` `",""))` (I just had this handy from doing the same this morning :) )
> > Figure 2: Looks good, can you make the abstract section a bit denser? Can you add something to clarify that you are testing on an independent set that was not used for feature selection in (iv/v)?
> > Figure 3: same comments as 2B.
> 
> This is a really hard comment to format with all the backticks but hopefully it's easy enough to copy and paste...haha

Thanks a bunch for the snippet! made life so much easier for me! :)

**Pull request merged**
