### PR TITLE
moving files

### PR DESCRIPTION
**Pull request by allaway**
I reran the drug target enrichment analysis but only considered approved (ie. true) drugs (list obtained from DrugCentral). This didn't work out super well, only a few drugs enriched, and they are mostly the same drugs for each LV.

### CODE REVIEW

**Comment by allaway** [comment]
> love the bar plots, will look better when we filter drug names....

This one is for the filtered analysis, as well as the markdown we were just looking at, sorry, I didnt fill in the PR description quick enough :)

**Comment by allaway** [comment]
@sgosline http://htmlpreview.github.io/?https://raw.githubusercontent.com/Sage-Bionetworks/NF_LandscapePaper_2019/d0f089b43fa88fcd60fc5b13e84f05318e4e1fd0/results/31-viper-drug-enrichment-bydrug_Approved_only.html

**Comment by jaybee84** [comment]
seems like sunitnib (that has come up multiple times) is in the clinical trials for both NF2 as well as NF1 (pNFs)

**Comment by jaybee84** [comment]
NF2: https://www.nf2is.org/sunitinib.php
NF1: https://clinicaltrials.gov/ct2/show/NCT01402817 (this was terminated due to patient death related to drug)

**Comment by sgosline** [comment]
Ahh, my git fetch didn't work at first. I think the only issue is that the dot plots look strange with so few dots. Would it be useful to use the qvalue instead of the p.adjust?

**Comment by allaway** [comment]
We can try changing the threshold - or - as we discussed in person just now
- try a bigger list of drugs (but not as big as the first list, where we
were looking at all of the target space). I think filtering for
FDA-approved drugs cost us a lot of target diversity, so we get a lot of
the same drugs with the same few targets...

**Comment by allaway** [comment]
> where we were looking at all of the target space

Er, i mean, all of the chemical space for which we have targets.

**Pull request merged**
